nelmio_cors:
    defaults:
        allow_origin: ['*'] 
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': # apply this config to all routes starting with /api/
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Authorization']
            max_age: 3600
            allow_credentials: true
