security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern: ^/api/user/login
            stateless: true
            json_login:
                check_path: /api/user/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/(api|coffres)  
            stateless: true
            jwt: 
                provider: app_user_provider  
            context: security.context 
        main:
            stateless: true
            jwt: ~
            json_login: ~

    access_control:
        - { path: ^/api/user/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/user/login, roles: PUBLIC_ACCESS }
        - { path: ^/coffres/create, roles: ROLE_USER }
        - { path: ^/coffres/\d+/regenerate-code, roles: ROLE_USER }